int a = 5;
int b = 3;
bool igual = a == b;
bool diferente = a != b;
bool maiorQue = a > b;
bool menorQue = a < b;
bool maiorOuIgual = a >= b;
bool menorOuIgual = a <= b;
Console.WriteLine("Valor de 'igual': " + igual);
Console.WriteLine("Valor de 'diferente': " + diferente);
Console.WriteLine("Valor de 'maiorQue': " + maiorQue);
Console.WriteLine("Valor de 'menorQue': " + menorQue);
Console.WriteLine("Valor de 'maiorOuIgual': " + maiorOuIgual);
Console.WriteLine("Valor de 'menorOuIgual': " + menorOuIgual);
